-- ============================================================================
-- Sprint W3 · Atto 1 · Migration M1
-- EVALOBI table + history (lifecycle: mint · transfer · re-evaluate)
-- ============================================================================
-- LOCKED decisions ref (Skeezu sealed 13 May 2026 night):
-- #5 Output GO: 1 EVALOBI Livello B + 1 ROBI bonus (soft-launch flag)
-- #6 Lifecycle: permanente eterno · trasferibile · re-evaluable opzionale
-- #10 NO_GO: EVALOBI emesso COMUNQUE con evaluation_outcome=NO_GO (pollution layer)
-- #17 Stack: Vercel SSR /api/evalobi-ssr.js (NOT CF Worker) — public_url path canonical
--
-- token_id BIGINT IDENTITY (Skeezu approved · on-chain compatible Stage 2 mapping)
-- ============================================================================

-- 1. Main EVALOBI table
CREATE TABLE public.evalobi (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  current_owner_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  original_seller_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

  -- Object metadata (Livello B)
  object_title TEXT NOT NULL,
  object_brand TEXT NOT NULL,
  object_model TEXT NOT NULL,
  object_condition TEXT NOT NULL CHECK (object_condition IN ('nuovo','come_nuovo','usato_eccellente')),
  object_year INTEGER,
  object_category TEXT NOT NULL,
  object_photo_hashes JSONB,

  -- Evaluation outcome
  evaluation_outcome TEXT NOT NULL CHECK (evaluation_outcome IN ('GO','NO_GO','NEEDS_REVIEW')),
  evaluation_price_range JSONB,
  evaluation_reasoning TEXT,
  evaluation_admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Versioning (re-evaluation support)
  version INTEGER NOT NULL DEFAULT 1,
  supersedes_evalobi_id UUID REFERENCES public.evalobi(id) ON DELETE SET NULL,

  -- Privacy controls (Area 6 pollution layer · opt-out granular)
  public_visible BOOLEAN NOT NULL DEFAULT TRUE,
  photo_blur_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  owner_redacted BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_evalobi_owner ON public.evalobi(current_owner_id);
CREATE INDEX idx_evalobi_original_seller ON public.evalobi(original_seller_id);
CREATE INDEX idx_evalobi_outcome ON public.evalobi(evaluation_outcome);
CREATE INDEX idx_evalobi_token_id ON public.evalobi(token_id);
CREATE INDEX idx_evalobi_public_visible ON public.evalobi(public_visible) WHERE public_visible = TRUE;

COMMENT ON TABLE public.evalobi IS 'AIROOBI EVALOBI · perpetual evaluation certificate (Livello B). Minted on every admin decision (GO/NO_GO/NEEDS_REVIEW). Pollution layer enabled via public SSR page airoobi.com/evalobi/{token_id}.';

-- 2. Append-only history (transfer · re-evaluation chain · airdrop participation)
CREATE TABLE public.evalobi_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  evalobi_id UUID NOT NULL REFERENCES public.evalobi(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('minted','transferred','re_evaluated','superseded','airdrop_listed','airdrop_settled')),
  event_metadata JSONB,
  prev_owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  new_owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  triggered_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_evalobi_history_evalobi ON public.evalobi_history(evalobi_id, occurred_at DESC);
CREATE INDEX idx_evalobi_history_event ON public.evalobi_history(event_type);

COMMENT ON TABLE public.evalobi_history IS 'Append-only event log for EVALOBI lifecycle. NEVER UPDATE/DELETE rows · only INSERT via SECURITY DEFINER RPCs.';

-- 3. RLS enable
ALTER TABLE public.evalobi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evalobi_history ENABLE ROW LEVEL SECURITY;

-- 4. RLS policies · evalobi
-- Owner reads own current
CREATE POLICY "Owner can read own evalobi"
  ON public.evalobi
  FOR SELECT
  TO authenticated
  USING (current_owner_id = auth.uid());

-- Original seller reads even after transfer (historical visibility)
CREATE POLICY "Original seller can read historical evalobi"
  ON public.evalobi
  FOR SELECT
  TO authenticated
  USING (original_seller_id = auth.uid());

-- Public visibility · pollution layer (anonymous can see if public_visible AND outcome decided)
CREATE POLICY "Anon can read public visible evalobi"
  ON public.evalobi
  FOR SELECT
  TO anon
  USING (public_visible = TRUE AND evaluation_outcome IS NOT NULL);

CREATE POLICY "Authenticated can read public visible evalobi"
  ON public.evalobi
  FOR SELECT
  TO authenticated
  USING (public_visible = TRUE AND evaluation_outcome IS NOT NULL);

-- Admin reads all
CREATE POLICY "Admin can read all evalobi"
  ON public.evalobi
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- Owner can update own privacy controls only
CREATE POLICY "Owner can update privacy flags"
  ON public.evalobi
  FOR UPDATE
  TO authenticated
  USING (current_owner_id = auth.uid())
  WITH CHECK (current_owner_id = auth.uid());

-- INSERT only via SECURITY DEFINER RPCs (no direct policy)
-- DELETE forbidden (RESTRICT FK + zero policy)

-- 5. RLS policies · evalobi_history
CREATE POLICY "Users can read history of own evalobi"
  ON public.evalobi_history
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.evalobi e
      WHERE e.id = evalobi_history.evalobi_id
        AND (e.current_owner_id = auth.uid() OR e.original_seller_id = auth.uid())
    )
  );

CREATE POLICY "Anon can read history of public evalobi"
  ON public.evalobi_history
  FOR SELECT
  TO anon
  USING (
    EXISTS (
      SELECT 1 FROM public.evalobi e
      WHERE e.id = evalobi_history.evalobi_id
        AND e.public_visible = TRUE
    )
  );

CREATE POLICY "Admin can read all evalobi_history"
  ON public.evalobi_history
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- INSERT only via SECURITY DEFINER RPCs (M2)
-- NEVER UPDATE/DELETE (append-only)

-- 6. GRANTs · Supabase Data API exposure (mandatory per default flip 30 Oct 2026)
GRANT SELECT ON TABLE public.evalobi TO authenticated;
GRANT SELECT ON TABLE public.evalobi TO anon;
GRANT UPDATE (public_visible, photo_blur_enabled, owner_redacted) ON TABLE public.evalobi TO authenticated;

GRANT SELECT ON TABLE public.evalobi_history TO authenticated;
GRANT SELECT ON TABLE public.evalobi_history TO anon;

-- 7. Comment on key columns
COMMENT ON COLUMN public.evalobi.token_id IS 'BIGINT IDENTITY · 1:1 mapping target for Stage 2 on-chain tokenId. No gaps allowed, no recycling.';
COMMENT ON COLUMN public.evalobi.evaluation_outcome IS 'GO=marketplace-ready · NO_GO=below quality threshold (EVALOBI still minted for pollution layer) · NEEDS_REVIEW=admin requested additional info';
COMMENT ON COLUMN public.evalobi.public_visible IS 'Default TRUE · seller can opt-out from public airoobi.com/evalobi/{token_id} page';
